apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: bulletinapi
  name: bulletinapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bulletinapi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: bulletinapi
    spec:
      containers:
      - image: penovak/bulletinapi:v1
        imagePullPolicy: ""
        name: bulletinapi
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /go/src/bulletinApi
          name: bulletinapi-claim0
      hostname: bulletinapi
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: bulletinapi-claim0
        persistentVolumeClaim:
          claimName: bulletinapi-claim0
status: {}
