version: '3'

services:
  db:
    container_name: bulletindb
    image: postgres:12
    hostname: db
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
  bulletinapi:
    container_name: bulletinapi
    image: penovak/bulletinapi:v1
    hostname: bulletinapi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/bulletinApi
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    labels:
      kompose.service.type: LoadBalancer